### ISSUE TITLE
Sept 13 update

### ISSUE THREAD

**Issue by Occy88** [ohyeah521/NoAds-For-YouTube#22]
App closes normally after exit (post sept update 10h or so before this post)
(I decided to downgrade again but the issue seems to persist)
Galaxy S9  v2.0.9 Youtube v 14.36.56(after downgrade) v14.36.57
failure observed on update and on downgrade, perhaps im doing something wrong.
I would like to help with the development of this project in my own time (obviously only if you agree)
feel free contact me.

**Comment by ohyeah521** [comment]
@Occy88  The next version will fix it. This is a bug. The next version will get configuration information from the cloud instead of generating hook information from the user to avoid exceptions on different models. Android fragmentation is too serious.Follow-up will provide special features such as downloading videos, so users will need to register, pay for, and the revenue will be used to purchase servers, etc.

**Comment by Occy88** [comment]
@ohyeah521 Ok, great idea btw with video downloading.
 I will close the issue as it somehow resolved itself...
anyway the offer of help still stands if you ever need it.
