### ISSUE TITLE
Not working on youtube 14.28.54

### ISSUE THREAD

**Issue by ayuu5h** [ohyeah521/NoAds-For-YouTube#8]
Phone model:Redmi 6 Pro
Sdk:28
Manufacturer:Xiaomi
Rom:aosip

**Comment by ohyeah521** [comment]
i had fix it. try again. thank you for you report.



ohyeah521@gmail.com
 
From: ayuu5h
Date: 2019-07-22 04:54
To: ohyeah521/NoAds-For-YouTube
CC: Subscribed
Subject: [ohyeah521/NoAds-For-YouTube] Not working on youtube 14.28.54 (#8)
Phone model:Redmi 6 Pro
Sdk:28
Manufacturer:Xiaomi
Rom:aosip

**Comment by ayuu5h** [comment]
Yes it works now.Thanks a lot for the module and more thanks for keeping it working and up to date.But may i know how it suddenly started working when i didn't update the module and infact there's no module update in xposed.

**Comment by ohyeah521** [comment]
I've adapted the new version because the app automatically gets the configuration information for the new version from the cloud, so you don't have to do anything to work as it did before.



ohyeah521@gmail.com
 
From: ayuu5h
Date: 2019-07-23 00:49
To: ohyeah521/NoAds-For-YouTube
CC: ohyeah521; Comment
Subject: Re: [ohyeah521/NoAds-For-YouTube] Not working on youtube 14.28.54 (#8)
Yes it works now.Thanks a lot for the module and more thanks for keeping it working and up to date.But may i know how it suddenly started working when i didn't update the module and infact there's no module update in xposed.
